### ISSUE TITLE
Tool: OCR using Tesseract

### ISSUE THREAD

**Issue by programmingninjas** [programmingninjas/GPT-3.5-ON-STEROIDS#10]
Python OCR is a technology that recognizes and pulls out text in images like scanned documents and photos using Python. It can be completed using the open-source OCR engine Tesseract. By integrating it our agent will be able to analyze and understand images better which will increase it's overall intelligence.
[Reference](https://builtin.com/data-science/python-ocr)

**Comment by fizakhan90** [comment]
please assign this issue to me

**Comment by programmingninjas** [comment]
Sure! Go for it.

**Comment by adityachoudhury29** [comment]
Would like to contribute to this issue for swoc24!

**Comment by programmingninjas** [comment]
@adityachoudhury29 sure you can! Kindly set up the project locally and make sure you understand it thoroughly. Good Luck!

**Comment by Ashinee-20** [comment]
Hey @programmingninjas, I would like to contribute to this issue

**Comment by programmingninjas** [comment]
@Ashinee-20 sorry ashinee but aditya asked for it first as you can already see so you have to look for an issue which is assigned to none or come up with your own issue (which can be any type of improvement in the existing project)

**Comment by Ashinee-20** [comment]
No problem :)

**Comment by programmingninjas** [comment]
@adityachoudhury29 Assigned you the issue! Start working on them
