### ISSUE TITLE
[Feature Request]: add codeql workflow

### ISSUE THREAD

**Issue by harmeetsingh11** [programmingninjas/GPT-3.5-ON-STEROIDS#20]
### Is your feature request related to a problem? Please describe. 

The repository contains code in `python`, it does not have workflow for code scanning. 

### Describe the solution you'd like 

I want to add the codeql workflow to automate security checks. CodeQL is the code analysis engine developed by GitHub to identify vulnerabilities in code. It will analyze your code and display the results as code scanning alerts. It will be enabled on every push, commit and pull request using GitHub actions. 

### Record 

- [x] I agree to follow this project's Code of Conduct 
- [x] I'm a SWOC 4.0 contributor
- [x] I want to work on this issue

**Comment by programmingninjas** [comment]
@harmeetsingh11 That will be a great add harmeet ! Go for it.

**Comment by programmingninjas** [comment]
@harmeetsingh11 As i don't have any knowledge about CodeQl. I asked Chatgpt to review the code content and it asked me why are you using swift repository when the project is of python. Something like this. So kindly check and let me know if it's fine the way it is

**Comment by harmeetsingh11** [comment]
@programmingninjas you are right. Thanks for pointing it out. Updated the workflow, please review it.
