### ISSUE TITLE
Also provide the final output to the user instead of just thoughts.

### ISSUE THREAD

**Issue by Prayag2** [programmingninjas/GPT-3.5-ON-STEROIDS#6]
Right now, the app just displays the "thoughts" of GPT-3.5. When the user asks questions, it does not give them the final output after completion. I think it might be beneficial for users if the program lets them know that these are just thoughts and not the actual answer their question.

I've thought of two solutions to this problem.
1. We can go the "Bing" way by showing the user text like "Searching on google", "Searching Wikipedia", "Writing to file", "Reading from file" instead of showing the entire thought process of GPT. After it completes, we can show the final output to the user.
2. We can hide the thoughts entirely and just show a loading indicator. After it completes, we can show the final output to the user.

What do you think? :D

**Comment by programmingninjas** [comment]
Thought process is important for users as it might contain valuable information. So we can't.
